import type {
  Membro,
  Transacao,
  Comunidade,
  Grupo,
  Notificacao,
  Agente,
  ActivityLogEntry,
  ScorePredictao,
  ScoreAlert,
} from "@/types";

export const MEMBROS: Membro[] = [
  {
    id: 1,
    nome: "Conceição Mateus",
    tel: "+244 923 456 789",
    posicao: 1,
    totalPoupado: 40000,
    score: 891,
    status: "Pago",
    iniciais: "CM",
    cor: "#FF5C1A",
    meses: 8,
    pontualidade: 94,
  },
  {
    id: 2,
    nome: "Manuel Jacinto",
    tel: "+244 912 345 678",
    posicao: 7,
    totalPoupado: 35000,
    score: 847,
    status: "Pago",
    iniciais: "MJ",
    cor: "#1D4ED8",
    meses: 8,
    pontualidade: 92,
  },
  {
    id: 3,
    nome: "Ana Paula Ferreira",
    tel: "+244 934 567 890",
    posicao: 3,
    totalPoupado: 40000,
    score: 823,
    status: "Pago",
    iniciais: "AP",
    cor: "#16A34A",
    meses: 7,
    pontualidade: 90,
  },
  {
    id: 4,
    nome: "Rosa Amélia Santos",
    tel: "+244 945 678 901",
    posicao: 9,
    totalPoupado: 30000,
    score: 756,
    status: "Pendente",
    iniciais: "RS",
    cor: "#F5A623",
    meses: 6,
    pontualidade: 85,
  },
  {
    id: 5,
    nome: "Filipe Mendes",
    tel: "+244 956 789 012",
    posicao: 5,
    totalPoupado: 40000,
    score: 801,
    status: "Pago",
    iniciais: "FM",
    cor: "#7C3AED",
    meses: 8,
    pontualidade: 91,
  },
  {
    id: 6,
    nome: "Lurdes Baptista",
    tel: "+244 967 890 123",
    posicao: 11,
    totalPoupado: 20000,
    score: 612,
    status: "Em atraso",
    iniciais: "LB",
    cor: "#DC2626",
    meses: 4,
    pontualidade: 67,
  },
  {
    id: 7,
    nome: "Domingos Neto",
    tel: "+244 978 901 234",
    posicao: 2,
    totalPoupado: 35000,
    score: 778,
    status: "Pago",
    iniciais: "DN",
    cor: "#0891B2",
    meses: 7,
    pontualidade: 88,
  },
  {
    id: 8,
    nome: "Esperança Lima",
    tel: "+244 989 012 345",
    posicao: 6,
    totalPoupado: 40000,
    score: 834,
    status: "Pago",
    iniciais: "EL",
    cor: "#059669",
    meses: 8,
    pontualidade: 93,
  },
  {
    id: 9,
    nome: "Carlos Futila",
    tel: "+244 990 123 456",
    posicao: 12,
    totalPoupado: 15000,
    score: 445,
    status: "Em atraso",
    iniciais: "CF",
    cor: "#B45309",
    meses: 3,
    pontualidade: 50,
  },
  {
    id: 10,
    nome: "Beatriz Capita",
    tel: "+244 901 234 567",
    posicao: 8,
    totalPoupado: 30000,
    score: 790,
    status: "Pendente",
    iniciais: "BC",
    cor: "#BE185D",
    meses: 6,
    pontualidade: 83,
  },
  {
    id: 11,
    nome: "João Kussumua",
    tel: "+244 912 890 123",
    posicao: 4,
    totalPoupado: 40000,
    score: 867,
    status: "Pago",
    iniciais: "JK",
    cor: "#6D28D9",
    meses: 8,
    pontualidade: 93,
  },
  {
    id: 12,
    nome: "Fernanda Agostinho",
    tel: "+244 923 901 234",
    posicao: 10,
    totalPoupado: 25000,
    score: 723,
    status: "Pago",
    iniciais: "FA",
    cor: "#0F766E",
    meses: 5,
    pontualidade: 80,
  },
];

export const HISTORICO: Transacao[] = [
  {
    id: 1,
    data: "15/05/2026",
    membro: "Conceição Mateus",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0515-001",
    status: "Pago",
  },
  {
    id: 2,
    data: "14/05/2026",
    membro: "Manuel Jacinto",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0514-002",
    status: "Pago",
  },
  {
    id: 3,
    data: "13/05/2026",
    membro: "Ana Paula Ferreira",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0513-003",
    status: "Pago",
  },
  {
    id: 4,
    data: "12/05/2026",
    membro: "Filipe Mendes",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0512-005",
    status: "Pago",
  },
  {
    id: 5,
    data: "10/05/2026",
    membro: "Domingos Neto",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0510-007",
    status: "Pago",
  },
  {
    id: 6,
    data: "09/05/2026",
    membro: "Esperança Lima",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0509-008",
    status: "Pago",
  },
  {
    id: 7,
    data: "08/05/2026",
    membro: "João Kussumua",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0508-011",
    status: "Pago",
  },
  {
    id: 8,
    data: "07/05/2026",
    membro: "Fernanda Agostinho",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0507-012",
    status: "Pago",
  },
  {
    id: 9,
    data: "01/05/2026",
    membro: "Lurdes Baptista",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0501-006",
    status: "Em atraso",
  },
  {
    id: 10,
    data: "01/05/2026",
    membro: "Carlos Futila",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0501-009",
    status: "Em atraso",
  },
  {
    id: 11,
    data: "01/04/2026",
    membro: "Conceição Mateus",
    tipo: "Recebimento",
    valor: 60000,
    ref: "KXP-REC-0401",
    status: "Recebido",
  },
  {
    id: 12,
    data: "28/03/2026",
    membro: "Sistema",
    tipo: "Lembrete SMS",
    valor: 0,
    ref: "KXP-SMS-0328",
    status: "Enviado",
  },
  {
    id: 13,
    data: "01/03/2026",
    membro: "Lurdes Baptista",
    tipo: "Contribuição",
    valor: 5000,
    ref: "KXP-0301-006",
    status: "Recuperado",
  },
  {
    id: 14,
    data: "01/02/2026",
    membro: "Domingos Neto",
    tipo: "Recebimento",
    valor: 60000,
    ref: "KXP-REC-0201",
    status: "Recebido",
  },
  {
    id: 15,
    data: "01/01/2026",
    membro: "Ana Paula Ferreira",
    tipo: "Recebimento",
    valor: 60000,
    ref: "KXP-REC-0101",
    status: "Recebido",
  },
];

export const COMUNIDADES: Comunidade[] = [
  {
    id: 1,
    nome: "Kixikila Rangel",
    regiao: "Luanda",
    membros: 12,
    maxMembros: 12,
    valorMensal: 5000,
    codigo: "KXRNG-2024",
    descricao: "Grupo do bairro Rangel · Rotação mensal",
  },
  {
    id: 2,
    nome: "Poupança Benguela",
    regiao: "Benguela",
    membros: 8,
    maxMembros: 15,
    valorMensal: 3000,
    codigo: "PBNGL-2025",
    descricao: "Grupo de comerciantes · Rotação quinzenal",
  },
  {
    id: 3,
    nome: "Kixikila Huambo",
    regiao: "Huambo",
    membros: 10,
    maxMembros: 12,
    valorMensal: 4000,
    codigo: "KXHBO-2025",
    descricao: "Grupo da centralidade · 2 vagas disponíveis",
  },
  {
    id: 4,
    nome: "Solidariedade Luanda Sul",
    regiao: "Luanda",
    membros: 6,
    maxMembros: 10,
    valorMensal: 7500,
    codigo: "SLS-2026",
    descricao: "Grupo empresarial · Vagas abertas",
  },
  {
    id: 5,
    nome: "Kixikila Kilamba",
    regiao: "Luanda",
    membros: 9,
    maxMembros: 12,
    valorMensal: 5000,
    codigo: "KKLB-2025",
    descricao: "Residenciais Kilamba · 3 vagas",
  },
  {
    id: 6,
    nome: "Poupança Lobito",
    regiao: "Benguela",
    membros: 5,
    maxMembros: 10,
    valorMensal: 2500,
    codigo: "PLBT-2026",
    descricao: "Grupo do Lobito · 5 vagas disponíveis",
  },
  {
    id: 7,
    nome: "Kixikila Malanje",
    regiao: "Malanje",
    membros: 7,
    maxMembros: 12,
    valorMensal: 3500,
    codigo: "KXMAL-2025",
    descricao: "Grupo aberto · 5 vagas disponíveis",
  },
  {
    id: 8,
    nome: "União Lubango",
    regiao: "Huíla",
    membros: 4,
    maxMembros: 10,
    valorMensal: 5000,
    codigo: "ULBN-2026",
    descricao: "Novo grupo · 6 vagas",
  },
];

export const REGIOES = [...new Set(COMUNIDADES.map((c) => c.regiao))].sort();

export const GRUPO_MOCK: Grupo = {
  id: "KXRNG-2024",
  nome: "Kixikila Rangel",
  codigo: "KXRNG-2024",
  valorMensal: 5000,
  diaCorte: 15,
  membros: MEMBROS,
  createdAt: "Setembro 2025",
};

export const NOTIFICACOES: Notificacao[] = [
  {
    id: 1,
    tipo: "pagamento",
    mensagem: "Ana Paula pagou a contribuição de Maio",
    lida: false,
    data: "15/05/2026",
  },
  {
    id: 2,
    tipo: "lembrete",
    mensagem: "Rosa Amélia tem pagamento pendente",
    lida: false,
    data: "14/05/2026",
  },
  {
    id: 3,
    tipo: "recebimento",
    mensagem: "Manuel vai receber em Junho — 60.000 Kz",
    lida: false,
    data: "13/05/2026",
  },
  {
    id: 4,
    tipo: "convite",
    mensagem: "Novo membro solicitou entrada no grupo",
    lida: true,
    data: "12/05/2026",
  },
];

export const AGENTES: Agente[] = [
  {
    id: 1,
    nome: "Maria Agostinho",
    telefone: "+244 900 000 002",
    email: "maria@kixipay.ao",
    regiao: "Luanda",
    status: "activo",
    membrosCadastrados: 47,
    scoreMedioAgente: 742,
    taxaRetencao: 89,
    metaMensal: 20,
    atingidoEsteMes: 14,
    dataContratacao: "Jan 2025",
    iniciais: "MA",
    cor: "#8B5CF6",
    gruposAssociados: ["KXRNG-2024", "SLS-2026", "KKLB-2025"],
  },
  {
    id: 2,
    nome: "Pedro Kussumua",
    telefone: "+244 900 000 003",
    email: "pedro@kixipay.ao",
    regiao: "Benguela",
    status: "activo",
    membrosCadastrados: 32,
    scoreMedioAgente: 689,
    taxaRetencao: 76,
    metaMensal: 20,
    atingidoEsteMes: 11,
    dataContratacao: "Mar 2025",
    iniciais: "PK",
    cor: "#EC4899",
    gruposAssociados: ["PBNGL-2025", "PLBT-2026"],
  },
  {
    id: 3,
    nome: "Helena Muxito",
    telefone: "+244 900 000 004",
    email: "helena@kixipay.ao",
    regiao: "Huambo",
    status: "activo",
    membrosCadastrados: 18,
    scoreMedioAgente: 651,
    taxaRetencao: 82,
    metaMensal: 15,
    atingidoEsteMes: 10,
    dataContratacao: "Jun 2025",
    iniciais: "HM",
    cor: "#06B6D4",
    gruposAssociados: ["KXHBO-2025"],
  },
  {
    id: 4,
    nome: "José Mavinga",
    telefone: "+244 900 000 005",
    email: "jose@kixipay.ao",
    regiao: "Malanje",
    status: "activo",
    membrosCadastrados: 12,
    scoreMedioAgente: 602,
    taxaRetencao: 71,
    metaMensal: 15,
    atingidoEsteMes: 5,
    dataContratacao: "Set 2025",
    iniciais: "JM",
    cor: "#F59E0B",
    gruposAssociados: ["KXMAL-2025"],
  },
  {
    id: 5,
    nome: "Lucia Tchilala",
    telefone: "+244 900 000 006",
    email: "lucia@kixipay.ao",
    regiao: "Huíla",
    status: "inactivo",
    membrosCadastrados: 8,
    scoreMedioAgente: 578,
    taxaRetencao: 63,
    metaMensal: 15,
    atingidoEsteMes: 2,
    dataContratacao: "Nov 2025",
    iniciais: "LT",
    cor: "#10B981",
    gruposAssociados: ["ULBN-2026"],
  },
];

export const ACTIVITY_LOG: ActivityLogEntry[] = [
  {
    id: 1,
    tipo: "criacao",
    entidade: "membro",
    entidadeId: "13",
    descricao: "Novo membro cadastrado: João Chimuco",
    responsavel: "Maria Agostinho",
    data: "15/05/2026 09:32",
  },
  {
    id: 2,
    tipo: "actualizacao",
    entidade: "grupo",
    entidadeId: "KXRNG-2024",
    descricao: "Valor mensal actualizado para 7.500 Kz",
    responsavel: "Conceição Mateus",
    data: "15/05/2026 10:15",
  },
  {
    id: 3,
    tipo: "alerta",
    entidade: "sistema",
    entidadeId: "AI-001",
    descricao: "Score de Carlos Futila abaixo de 450 — acção recomendada",
    responsavel: "Sistema IA",
    data: "14/05/2026 23:00",
  },
  {
    id: 4,
    tipo: "registo",
    entidade: "agente",
    entidadeId: "6",
    descricao: "Novo agente registado: Ana Burity (Luanda)",
    responsavel: "Administrador",
    data: "14/05/2026 16:45",
  },
  {
    id: 5,
    tipo: "remocao",
    entidade: "membro",
    entidadeId: "14",
    descricao: "Membro removido do grupo: Zeca Ngola (inactivo 3 meses)",
    responsavel: "Conceição Mateus",
    data: "13/05/2026 14:20",
  },
  {
    id: 6,
    tipo: "login",
    entidade: "coordenador",
    entidadeId: "conceicao",
    descricao: "Login de Conceição Mateus",
    responsavel: "Conceição Mateus",
    data: "15/05/2026 08:00",
  },
  {
    id: 7,
    tipo: "actualizacao",
    entidade: "sistema",
    entidadeId: "SCORE-001",
    descricao: "Modelo de IA actualizado — nova versão 2.3.1",
    responsavel: "Sistema IA",
    data: "13/05/2026 02:00",
  },
  {
    id: 8,
    tipo: "criacao",
    entidade: "grupo",
    entidadeId: "ULBN-2026",
    descricao: "Novo grupo criado: União Lubango",
    responsavel: "Helena Muxito",
    data: "12/05/2026 11:30",
  },
];

export const SCORE_PREDICOES: ScorePredictao[] = [
  {
    membroId: 1,
    membroNome: "Conceição Mateus",
    scoreActual: 891,
    scoreProjectado: 912,
    tendencia: "subindo",
    confianca: 0.92,
    factores: [
      {
        factor: "Pontualidade",
        impacto: "positivo",
        peso: 35,
        descricao: "94% de pagamentos a tempo",
      },
      { factor: "Tempo de conta", impacto: "positivo", peso: 25, descricao: "8 meses activo" },
      { factor: "Volume poupado", impacto: "positivo", peso: 20, descricao: "40.000 Kz total" },
    ],
    recomendacao: "Perfil excelente. Recomendar aumento de limite de crédito.",
    dataAnalise: "15/05/2026",
  },
  {
    membroId: 6,
    membroNome: "Lurdes Baptista",
    scoreActual: 612,
    scoreProjectado: 580,
    tendencia: "descendo",
    confianca: 0.78,
    factores: [
      {
        factor: "Pontualidade",
        impacto: "negativo",
        peso: 40,
        descricao: "67% — múltiplos atrasos",
      },
      { factor: "Tempo de conta", impacto: "positivo", peso: 15, descricao: "4 meses activo" },
      { factor: "Volume poupado", impacto: "neutro", peso: 10, descricao: "20.000 Kz" },
    ],
    recomendacao: "Risco elevado. Agendar visita do agente e activar lembretes SMS.",
    dataAnalise: "15/05/2026",
  },
  {
    membroId: 9,
    membroNome: "Carlos Futila",
    scoreActual: 445,
    scoreProjectado: 410,
    tendencia: "descendo",
    confianca: 0.85,
    factores: [
      {
        factor: "Pontualidade",
        impacto: "negativo",
        peso: 45,
        descricao: "50% — em atraso crónico",
      },
      { factor: "Tempo de conta", impacto: "negativo", peso: 20, descricao: "Apenas 3 meses" },
    ],
    recomendacao: "CRÍTICO. Contactar urgente. Se não responder em 7 dias, remover do grupo.",
    dataAnalise: "15/05/2026",
  },
  {
    membroId: 2,
    membroNome: "Manuel Jacinto",
    scoreActual: 847,
    scoreProjectado: 860,
    tendencia: "subindo",
    confianca: 0.88,
    factores: [
      {
        factor: "Pontualidade",
        impacto: "positivo",
        peso: 30,
        descricao: "92% de pagamentos a tempo",
      },
      { factor: "Tempo de conta", impacto: "positivo", peso: 20, descricao: "8 meses activo" },
    ],
    recomendacao: "Bom perfil. Elegível para novo grupo com valor superior.",
    dataAnalise: "15/05/2026",
  },
];

export const SCORE_ALERTAS: ScoreAlert[] = [
  {
    id: 1,
    membroId: 9,
    membroNome: "Carlos Futila",
    score: 445,
    tipo: "critico",
    mensagem: "Score abaixo de 450 — risco de exclusão do grupo",
    data: "14/05/2026",
    lido: false,
    accaoRecomendada: "Contactar membro urgentemente",
  },
  {
    id: 2,
    membroId: 6,
    membroNome: "Lurdes Baptista",
    score: 612,
    tipo: "atencao",
    mensagem: "Tendência de score negativa — 3 atrasos consecutivos",
    data: "14/05/2026",
    lido: false,
    accaoRecomendada: "Enviar lembrete e agendar visita",
  },
  {
    id: 3,
    membroId: 4,
    membroNome: "Rosa Amélia Santos",
    score: 756,
    tipo: "melhoria",
    mensagem: "Pontualidade pode melhorar — 2 pendentes este mês",
    data: "13/05/2026",
    lido: true,
    accaoRecomendada: "Oferta de educação financeira",
  },
];
